CREATE TABLE CONSTITUENCY(
CONSTID INT PRIMARY KEY,
NAME VARCHAR(30),
STATE VARCHAR(30),
NOOFVOTERS INT
);
INSERT INTO CONSTITUENCY VALUES (1, 'BANGALORE', 'KARNATAKA', 2);
INSERT INTO CONSTITUENCY VALUES (2, 'SHIMOGA', 'KARNATAKA', 2);
INSERT INTO CONSTITUENCY VALUES (3, 'HYDERABAD', 'TELANGANA', 3);

CREATE TABLE PARTY(
PID INT PRIMARY KEY,
PNAME VARCHAR(30),
SYMBOL VARCHAR(30)
);
INSERT INTO PARTY VALUES (1, 'CONGRESS', 'PALM');
INSERT INTO PARTY VALUES (2, 'BJP', 'LOTUS');

CREATE TABLE CANDIDATE(CANDID INT PRIMARY KEY,
NAME VARCHAR(30),PNO VARCHAR(30),
AGE INT,STATE VARCHAR(30),
PID INT REFERENCES PARTY(PID));
INSERT INTO CANDIDATE VALUES (1, 'AMAR', '8660639260', 35, 'KARNATAKA', 1);
INSERT INTO CANDIDATE VALUES (2, 'ANTONY', '8660639262', 37, 'TELANGANA', 2);

CREATE TABLE VOTERS(VID INT,NAME VARCHAR(30),
AGE INT,ADDRESS VARCHAR(150),
CONSTID INT REFERENCES CONSTITUENCY(CONSTID),
CANDID INT REFERENCES CANDIDATE(CANDID));
INSERT INTO VOTERS VALUES (1, 'ABHI', 20, '1 BALKI BIDAR KARNATAKA 577001', 1, 1);
INSERT INTO VOTERS VALUES (2, 'ARIF', 20, '1 BHADRAVATHI BHADRAVATHI KARNATAKA 577201', 2, 2);
INSERT INTO VOTERS VALUES (3, 'MANOJ', 18, '1 ANAVERI SHIMOGA KARNATAKA 577243', 1, 2);

CREATE TABLE CONTEST(
CONSTID INT REFERENCES CONSTITUENCY(CONSTID),CANDID INT REFERENCES CANDIDATE(CANDID)
);
INSERT INTO CONTEST VALUES (1, 1);
INSERT INTO CONTEST VALUES (2, 2);
INSERT INTO CONTEST VALUES (3, 1);


SELECT * FROM candidate WHERE candid IN (
SELECT candid FROM contest NATURAL JOIN constituency
GROUP BY candid
HAVING COUNT(DISTINCT state)>1);

select state from constituency group by state
having count(*)=(select max(count(*))
from constituency group by state);

create or replace procedure checkage(id number,age number) as
begin
if age>=18 then
insert into voters(vid,age)
values(id,age);
else
dbms_output.put_line('NOT ELIGIBLE');
end if;
end;
/
exec checkage(4,20);

create or replace procedure countvoters(id number) as
c number;
begin
select noofofvoters into c from constituency
where constid=id;
dbms_output.put_line(c);
end;
/
exec countvoters(1);

create or replace trigger updatecount
after insert on voters
for each row
begin
update constituency
set noofvoters=noofvoters+1
where constid=:new.constid;
end;
/
